const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { generate, target } = require('./sync-cairm-runtime.cjs');
const { naCheck, integrity } = require('../src/renderer/db-audit.js');
const { scan, hasProductData } = require('../src/renderer/db-audit.js');
const { cleanupSyntax } = require('../src/renderer/db-maintenance.js');
assert.equal(fs.readFileSync(target, 'utf8'), generate(), 'Audit engine must match production Cairm');
const zones = ['europe', 'usa', 'canada', 'hong_kong_taiwan', 'australia', 'rest_of_world'];
const zone = () => ({ rma: { status: 'yes', location: 'L1', paid: { status: 'no' } }, spare_parts: { status: 'yes' }, exchange: { status: 'no' } });
const fixture = () => ({ ids: { countries: { C1: { name: 'France' } }, products: { P1: { name: 'Device' } }, bundles: {}, locations: { L1: { name: 'Centre' } } }, countries: { C1: { ga_zone: 'europe', rma: { status: 'yes', warranty_duration: 2 }, spare_parts: { status: 'yes', warranty_duration: 2 } } }, products: { P1: { skus: { global: 'SKU1' }, zones: Object.fromEntries(zones.map(z => [z, zone()])) } } });
const base = fixture();
assert.equal(naCheck(base).cells, 0);
assert.equal(integrity(base).length, 0);
const commercial = fixture();
commercial.products.P1.zones.europe.rma.paid = { status: 'yes' };
for (const suffix of ['rma.paid.location', 'rma.paid.price', 'rma.default_transport_fee']) assert(integrity(commercial).some(row => row.path.endsWith(suffix)));
assert.equal(naCheck(commercial).cells, 0, 'Source completeness warnings must not be mislabeled N/A');
const gaps = fixture();
delete gaps.products.P1.zones.europe;
let report = naCheck(gaps);
assert.equal(report.cells, 4, 'A missing region produces four N/A cells');
assert.equal(report.affected, 1);
gaps.countries.C1.rma.status = 'no';
gaps.countries.C1.spare_parts.status = 'no';
gaps.countries.C1.exchange = { status: 'no' };
assert.equal(naCheck(gaps).cells, 0, 'Country restrictions suppress N/A, including legacy paid fallback');
delete gaps.countries.C1.rma.warranty_duration;
assert.equal(naCheck(gaps).cells, 1, 'Country warranty still renders under No');
assert(integrity(gaps).some(row => row.path.endsWith('warranty_duration')));
const important = fixture();
delete important.products.P1.zones.europe;
important.countries.C1.temporary_comment = { enabled: true, sections: ['rma', 'spare_parts', 'paid_rma', 'exchange'], comment: 'Review' };
assert.equal(naCheck(important).cells, 0, 'CHECK NOTE replaces N/A');
const inferred = fixture();
delete inferred.products.P1.zones.europe.rma.status;
delete inferred.products.P1.zones.europe.spare_parts.status;
inferred.products.P1.zones.europe.rma.paid = { price: 25 };
assert.equal(naCheck(inferred).cells, 0, 'Use actual country fallback and inferred paid status');
assert(integrity(inferred).some(row => row.path.endsWith('rma.status')), 'Source gaps remain visible in Scan DB');
const bundle = fixture();
bundle.ids.products.P2 = { name: 'Absent rules' };
bundle.ids.bundles.B1 = { name: 'Kit', products: ['P1', 'P2'] };
report = naCheck(bundle);
assert.equal(report.tested, 3);
assert.equal(report.cells, 8, 'Missing component renders in the product and its bundle');
assert(report.issues.every(row => row.occurrences.some(o => o.selectionId === 'B1')));
bundle.ids.bundles.B2 = { name: 'Broken', products: ['NONEXISTENT'] };
assert(naCheck(bundle).blockers.some(row => row.path === 'ids.bundles.B2.products'));
assert(integrity(bundle).some(row => row.path === 'ids.bundles.B2.products'));
const ambiguous = fixture();
ambiguous.ids.products.P2 = { name: 'Other', aliases: ['Device'] };
ambiguous.products.P2 = structuredClone(ambiguous.products.P1);
assert(naCheck(ambiguous).blockers.some(row => row.input === 'device'));
assert(integrity(ambiguous).some(row => row.reason.includes('ambigu')));
const orphan = fixture();
orphan.products.ORPHAN = structuredClone(orphan.products.P1);
orphan.products.P1.skus = { countries: { MISSING: 'sku' } };
orphan.products.P1.zones.europe.rma.extra_transport_fees = { MISSING: 10 };
orphan.checked = { products: { MISSING: true } };
const before = JSON.stringify(orphan);
const issues = integrity(orphan);
for (const path of ['products.ORPHAN', 'products.P1.skus.countries.MISSING', 'products.P1.zones.europe.rma.extra_transport_fees.MISSING', 'checked.products.MISSING']) assert(issues.some(row => row.path === path), path);
naCheck(orphan);
assert.equal(JSON.stringify(orphan), before, 'Both scans are read-only');
assert(integrity({ ids: {}, countries: { X: null }, products: { X: null }, activeBundles: [null] }).length > 0);

// Use the actual HTML renderer as an independent oracle for warranty N/A under No.
const source = fs.readFileSync(require.resolve('../../Cairm/extensions/cairm/content.js'), 'utf8');
const render = vm.createContext({ escapeHtml: value => String(value ?? ''), formatDocumentSignalsRichTextHtml: value => String(value ?? ''), translateCairnContent: (key, fallback) => fallback, normalizeComparableText: value => String(value || '').trim().toLowerCase() });
for (const name of ['formatDocumentSignalsDisplayText', 'getDocumentInfoTone', 'buildDocumentSignalsDetailRowHtml', 'formatWarrantyDuration']) {
  const start = source.indexOf(`  function ${name}(`);
  vm.runInContext(source.slice(start, source.indexOf('\n  }', start) + 4), render);
}
assert.match(render.buildDocumentSignalsDetailRowHtml('RMA warranty', render.formatWarrantyDuration(undefined), ''), /<strong>N\/A<\/strong>/);

// Opening/exporting must retain malformed references so the scan can see them.
const html = fs.readFileSync(require.resolve('../src/renderer/index.html'), 'utf8');
const ui = vm.createContext({});
const start = html.indexOf('      function normalizeDatabase(');
vm.runInContext(html.slice(start, html.indexOf('\n      }', start) + 8), ui);
const opened = structuredClone(orphan);
ui.normalizeDatabase(opened);
assert(opened.products.ORPHAN);
assert.equal(opened.products.P1.skus.countries.MISSING, 'sku');
assert.equal(opened.checked.products.MISSING, true);
assert.equal(opened.products.P1.zones.europe.rma.extra_transport_fees.MISSING, 10);
const real = JSON.parse(fs.readFileSync(require.resolve('../cairm-full-database.json'), 'utf8'));
assert(!real.ids.products.P535 && !real.products.P535, 'Duplicate removed');
assert.equal(require('../src/renderer/cairm-runtime.js').create(real).resolveProduct('TX 2 PEDAL SET IN WHITE BOX').id, 'P374');
assert.equal(require('../src/renderer/cairm-runtime.js').create(real).resolveProduct('2 Pedal Set').id, 'P374');
assert(real.products.P374.skus.global.includes('5076299') && real.products.P374.skus.global.includes('5076771'));
for (const id of ['B062', 'B064']) assert(real.ids.bundles[id].products.includes('P374'));
assert(!JSON.stringify(real).includes('P535'));
// The global queue merges categories by field and excludes truly empty products
// from N/A even when they occur as bundle components.
const global = fixture();
global.ids.products.EMPTY = { name: 'Empty product', _source: { file: 'legacy' } };
global.ids.products.SKU = { name: 'SKU only' };
global.products.SKU = { skus: { global: 'SKU' }, zones: {} };
global.ids.products.SKELETON = { name: 'Empty skeleton' };
global.products.SKELETON = { zones: { europe: { rma: { status: null }, spare_parts: {} } } };
global.ids.bundles.B1 = { name: 'Mixed bundle', products: ['P1', 'EMPTY'] };
delete global.products.P1.zones.europe;
global.products.P1.zones.usa.exchange.status = 'both';
global.products.P1.zones.canada.rma.status = 'maybe';
const globalBefore = JSON.stringify(global);
const globalReport = scan(global);
assert.equal(globalReport.complete, true);
assert.equal(globalReport.counts['no-data'], 3);
assert.equal(globalReport.tested, 2, 'Only the populated product and mixed bundle remain');
assert.equal(globalReport.cells, 8, 'Only populated P1 contributes four N/A in two selections');
assert(!globalReport.issues.some(row => row.categories.includes('na') && ['EMPTY', 'SKU', 'SKELETON'].includes(row.target.id)));
assert(globalReport.issues.some(row => row.path === 'products.P1.zones.europe' && row.categories.includes('partial')));
assert(!globalReport.issues.some(row => row.path === 'products.P1.zones.europe' && row.categories.includes('syntax')), 'Absent regions are partial data, not syntax');
assert(globalReport.issues.some(row => row.path.endsWith('canada.rma.status') && row.categories.includes('syntax') && !row.fixable));
assert(globalReport.issues.some(row => row.path.endsWith('usa.exchange.status') && row.categories.includes('syntax') && row.fixable));
assert.equal(JSON.stringify(global), globalBefore);
const cleaned = cleanupSyntax(global);
assert.equal(cleaned.db.products.P1.zones.usa.exchange.status, 'retailer');
assert.equal(cleaned.db.products.P1.zones.europe, undefined, 'Cleanup must not invent a region');
assert.equal(cleaned.db.products.SKELETON.zones.europe.rma.status, null, 'Cleanup must not replace a gap with No');
assert.equal(cleaned.db.products.P1.zones.canada.rma.status, 'maybe', 'Unknown business decisions need manual review');
assert.equal(cleaned.db.ids.products.EMPTY._source, undefined);
assert.equal(cleanupSyntax(cleaned.db).report.changes.length, 0, 'Syntax cleanup is idempotent');
assert.equal(hasProductData({ zones: { europe: { rma: { status: 'no' } } } }), true, 'An explicit No is data');
assert(scan(ambiguous).issues.some(row => row.categories.includes('not-resolved') && row.target.id === 'P1'));
const warrantyGap = fixture();
delete warrantyGap.countries.C1.rma.warranty_duration;
assert.deepEqual(scan(warrantyGap).issues.find(row => row.path === 'countries.C1.rma.warranty_duration').categories, ['partial', 'na']);
const malformed = scan({ ids: {}, countries: {}, products: {}, activeBundles: [null] });
assert(malformed.issues.length > 0);
console.log('Audit OK: production engine parity, N/A rendering, country restrictions, notes, paid inference, aliases, bundles, broken references, read-only scans and duplicate merge.');

const collisionBefore = JSON.stringify(ambiguous);
const collisionRows = scan(ambiguous).issues.filter(row => row.categories.includes('not-resolved'));
assert(collisionRows.length);
for (const row of collisionRows) {
  assert(row.suggestions.steps.some(step => step.includes('Aucune modification du CRM')));
  assert(row.suggestions.steps.some(step => step.includes('ne pas choisir arbitrairement')));
  assert(row.suggestions.related.some(link => link.path === 'ids.products.P1.aliases'));
  assert(row.suggestions.related.some(link => link.path === 'ids.products.P2.aliases'));
}
assert.equal(JSON.stringify(ambiguous), collisionBefore);
const orphanSuggestions = scan(orphan).issues;
assert(orphanSuggestions.find(row => row.path === 'products.P1.skus.countries.MISSING').suggestions.steps.some(step => step.includes('lecture seule')));
assert(orphanSuggestions.find(row => row.path === 'checked.products.MISSING').suggestions.steps.some(step => step.includes('Cleanup')));
assert.equal(JSON.stringify(orphan), before, 'Guidance must never mutate the database');
console.log('Unresolved guidance OK: collisions, related records, broken references and no CRM edits.');
