// Generated by scripts/sync-cairm-runtime.cjs. Do not edit.
(function(root) {
  function create(db) {
    let localServiceRules = {}, localServiceRulesState = {};
    const COUNTRY_TEMPORARY_COMMENT_SECTIONS = new Set(['spare_parts', 'rma', 'paid_rma', 'exchange']);
    // Notes do not determine availability; no DOM is required for the audit.
    const getHeaderSignalsNote = value => String(value ?? '').trim() === '0' ? '' : String(value ?? '').trim();
    const translateCairnContent = (key, fallback) => fallback;
  function normalizeText(value) {
    return (value || "").toLowerCase().trim();
  }

  function normalizeComparableText(value) {
    const normalized = normalizeText(value).replace(/\s+/g, " ");
    return typeof normalized.normalize == "function"
      ? normalized.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
      : normalized;
  }

  function normalizeLocalIdentityKey(value, type = "product") {
    let key = normalizeComparableText(String(value ?? ""))
      .replace(/[\u2018\u2019\u02bc]/g, "'")
      .replace(/[\u2010-\u2015\u2212]/g, "-");
    if (/^\{?[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\}?$/.test(key)) {
      return key.replace(/[{}]/g, "");
    }
    // Countries accept typography only; products retain separators, numbers and suffixes.
    if (type === "country") {
      key = key.replace(/-/g, " ").replace(/\s+/g, " ").trim();
      // Explicit bilingual equivalence, also supported by older databases without the short French alias.
      if (["etats unis", "etats unis d'amerique", "united states", "united states of america", "usa"].includes(key)) key = "united states";
    }
    return key;
  }

  function findLocalIdentityMatches(value, index) {
    if (!Array.isArray(index) || !String(value ?? "").trim()) return [];
    const matches = new Map();
    const countryKey = normalizeLocalIdentityKey(value, "country");
    const productKey = normalizeLocalIdentityKey(value, "product");
    for (const entry of index) {
      if (!entry || !entry.key) continue;
      const key = entry.type === "country" ? countryKey : productKey;
      if (entry.key === key) matches.set(`${entry.type === "country" ? "country" : entry.type === "product" ? "product" : "bundle"}:${entry.id}`, entry);
    }
    return [...matches.values()];
  }

  function pushLocalRuleAlias(index, id, record, type) {
    const aliases = new Set([
      record && record.name, record && record.label_fr, record && record.labelFr,
      ...(Array.isArray(record && record.aliases) ? record.aliases : typeof (record && record.aliases) === "string" ? [record.aliases] : [])
    ]);
    const keys = new Set();
    aliases.forEach((alias) => {
      if (typeof alias !== "string" && typeof alias !== "number") return;
      // Historical alias arrays can contain technical IDs; they are not display names.
      if (/^\{?[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\}?$/i.test(String(alias).trim()) || String(alias) === String(id)) return;
      const key = normalizeLocalIdentityKey(alias, type);
      if (key) {
        keys.add(key);
        // Existing compact country spellings are exact aliases, with collision checks.
        if (type === "country") keys.add(key.replace(/ /g, ""));
      }
    });
    keys.forEach((key) => index.push({ key, id, record, type }));
  }

  function resolveProductIdsFromActiveBundleComposition(composition, productIndex) {
    const chunks = String(composition || "")
      .split(/\s+\+\s+|\s*,\s*|\s+\/\s+/)
      .map(part => part.replace(/^\d+\s*x\s+/i, "").trim()).filter(Boolean);
    const productIds = [];
    for (const chunk of chunks) {
      const match = resolveExactLocalIndexEntry(chunk, productIndex);
      // Never build a partial bundle from a partially understood composition.
      if (!match) return [];
      if (!productIds.includes(match.id)) productIds.push(match.id);
    }
    return productIds;
  }

  function normalizeActiveBundleProductIds(value, ids) {
    if (!Array.isArray(value) || !value.length) return [];
    const knownProducts = (ids && ids.products) || {};
    const productIds = [];
    for (const valueId of value) {
      const id = typeof valueId === "string" ? valueId.trim() : "";
      if (!id || !Object.prototype.hasOwnProperty.call(knownProducts, id)) return [];
      if (!productIds.includes(id)) productIds.push(id);
    }
    return productIds;
  }

  function buildLocalServiceIndex(ids, activeBundles) {
    const countryIndex = [];
    const productIndex = [];
    const bundleIndex = [];
    const locationIndex = Object.create(null);
    Object.entries((ids && ids.countries) || {}).forEach(([id, record]) => {
      pushLocalRuleAlias(countryIndex, id, record, "country");
    });
    Object.entries((ids && ids.products) || {}).forEach(([id, record]) => {
      pushLocalRuleAlias(productIndex, id, record, "product");
    });
    const bundleRecords = new Map(Object.entries((ids && ids.bundles) || {}).map(([id, record]) => [id, {
      ...record, products: normalizeActiveBundleProductIds(record && record.products, ids)
    }]));
    (Array.isArray(activeBundles) ? activeBundles : []).forEach((bundle) => {
      if (!bundle || typeof bundle !== "object" || Array.isArray(bundle) || typeof bundle.id !== "string" || !bundle.id.trim()) return;
      const explicitProductIds = normalizeActiveBundleProductIds(bundle.products, ids);
      const previous = bundleRecords.get(bundle.id) || {};
      const record = {
        ...previous,
        name: bundle.name || previous.name,
        crm_id: bundle.crm_id || previous.crm_id,
        crm_ids: [...(Array.isArray(previous.crm_ids) ? previous.crm_ids : []), ...(Array.isArray(bundle.crm_ids) ? bundle.crm_ids : [])],
        aliases: [...(Array.isArray(previous.aliases) ? previous.aliases : typeof previous.aliases === "string" ? [previous.aliases] : []), ...(Array.isArray(bundle.aliases) ? bundle.aliases : []), previous.name, bundle.name].filter(Boolean),
        products: Object.prototype.hasOwnProperty.call(bundle, "products")
          ? explicitProductIds
          : resolveProductIdsFromActiveBundleComposition(bundle.composition, productIndex),
        active_bundle: true,
        identityAmbiguous: previous.active_bundle === true || previous.identityAmbiguous === true,
        _source: {
          file: "Bundles_PL_Thrustmaster_Hercules.csv",
          brand: bundle.brand,
          status: bundle.status,
          source: bundle.source,
          notes: bundle.notes,
          composition: bundle.composition
        }
      };
      bundleRecords.set(bundle.id, record);
    });
    bundleRecords.forEach((record, id) => pushLocalRuleAlias(bundleIndex, id, record, record.active_bundle ? "active-bundle" : "bundle"));
    Object.entries((ids && ids.locations) || {}).forEach(([id, record]) => {
      locationIndex[id] = (record && (record.name || (record.aliases && record.aliases[0]))) || id;
    });
    return { countryIndex, productIndex, bundleIndex, locationIndex };
  }

  function installLocalServiceRulesFromCairmDb(db) {
    if (!db || typeof db !== "object" || Array.isArray(db)) {
      throw new Error("CairmDB cache missing");
    }
    if (!db.countries || typeof db.countries !== "object" || Array.isArray(db.countries)) {
      throw new Error("CairmDB countries missing");
    }
    if (!db.products || typeof db.products !== "object" || Array.isArray(db.products)) {
      throw new Error("CairmDB products missing");
    }
    if (!db.ids || typeof db.ids !== "object" || Array.isArray(db.ids)) {
      throw new Error("CairmDB ids missing");
    }
    const activeBundles = Array.isArray(db.activeBundles) ? db.activeBundles : [];
    const index = buildLocalServiceIndex(db.ids, activeBundles);
    localServiceRules = {
      countries: db.countries,
      products: db.products,
      ids: db.ids,
      activeBundles,
      ...index
    };
    localServiceRulesState = {
      status: "fresh",
      error: ""
    };
    return localServiceRules;
  }

  function resolveLocalIndexEntry(value, index) {
    return resolveExactLocalIndexEntry(value, index);
  }

  function resolveExactLocalIndexEntry(value, index) {
    // CRM GUIDs are deliberately ignored: only a unique textual identity selects rules.
    const names = findLocalIdentityMatches(value, index);
    // An exact bundle name takes precedence over product names, never over another bundle.
    const bundles = names.filter(entry => entry.type === "bundle" || entry.type === "active-bundle");
    const candidates = bundles.length ? bundles : names;
    return candidates.length === 1 && !candidates[0].record?.identityAmbiguous ? candidates[0] : null;
  }

  function resolveLocalCountry(country) {
    const match = resolveExactLocalIndexEntry(country, localServiceRules.countryIndex);
    if (!match) return null;
    const rule = localServiceRules.countries?.[match.id];
    // The panel header must read exactly like the CRM country field. The database
    // name is only a fallback: showing label_fr instead would rename a country the
    // agent is looking at, and an identity is selected on the exact CRM text anyway.
    const crmName = String(country ?? "").trim();
    const canonicalName = (match.record && (match.record.name || match.record.label_fr)) || "";
    return {
      id: match.id,
      displayName: crmName || canonicalName || match.id,
      canonicalName: canonicalName || crmName || match.id,
      rule: rule || {},
      dataMissing: !rule
    };
  }

  function resolveLocalProductOrBundle(value) {
    const match = resolveExactLocalIndexEntry(value, [...(localServiceRules.productIndex || []), ...(localServiceRules.bundleIndex || [])]);
    if (!match) return null;
    const bundle = match.type !== "product";
    return {
      type: bundle ? "bundle" : "product", id: match.id,
      displayName: match.record?.name || value || match.id,
      productIds: bundle ? (Array.isArray(match.record?.products) ? match.record.products : []) : [match.id]
    };
  }

  function normalizeServiceStatus(value) {
    const normalized = normalizeComparableText(value);
    if (normalized === "yes") {
      return true;
    }
    if (normalized === "no") {
      return false;
    }
    if (normalized === "temp") {
      return "temp";
    }
    return null;
  }

  function formatWarrantyDuration(value) {
    if (value === null || value === undefined || value === "") {
      return "";
    }
    if (value === "check_retailer") {
      return "Check retailer";
    }
    if (Number.isFinite(Number(value))) {
      const years = Number(value);
      return years === 1 ? `${years} year` : `${years} years`;
    }
    return String(value);
  }

  function formatServicePrice(price, currencyOverride = "") {
    if (price === null || price === undefined) {
      return "";
    }
    if (typeof price === "string" || typeof price === "number") {
      const text = String(price).trim();
      return currencyOverride && /\s(?:EUR|€)\s*$/i.test(text)
        ? text.replace(/\s(?:EUR|€)\s*$/i, ` ${currencyOverride}`)
        : text;
    }
    if (typeof price !== "object" || price.amount === null || price.amount === undefined) {
      return "";
    }
    const amount = Number(price.amount);
    const rawAmount = Number.isFinite(amount) ? amount.toLocaleString("en-US") : String(price.amount);
    const sourceCurrency = String(price.currency || "").trim();
    const currency =
      currencyOverride && (!sourceCurrency || /^(?:EUR|€)$/i.test(sourceCurrency))
        ? currencyOverride
        : sourceCurrency;
    return `${rawAmount} ${currency}`.trim();
  }

  function getLocationLabel(locationId) {
    if (!locationId) {
      return "";
    }
    return localServiceRules.locationIndex[locationId] || locationId;
  }

  function combineServiceStatuses(values) {
    const known = values.filter((value) => value !== null && value !== undefined);
    if (!known.length) {
      return null;
    }
    if (known.some((value) => value === false)) {
      return false;
    }
    if (known.some((value) => value === "temp")) {
      return "temp";
    }
    if (known.length === values.length && known.every((value) => value === true)) {
      return true;
    }
    return null;
  }

  function combineServiceLevels(values) {
    const known = values.filter(Boolean);
    if (!known.length) {
      return "";
    }
    return known.includes("country") ? "country" : known[0];
  }

  function isRestrictiveCountryStatus(value) {
    return value === false || value === "temp";
  }

  function getCountryTemporaryCommentOverride(countryRule) {
    const source = countryRule && countryRule.temporary_comment;
    if (!source || typeof source !== "object" || source.enabled !== true) {
      return null;
    }
    const sections = new Set(
      (Array.isArray(source.sections) ? source.sections : [])
        .map((section) => String(section || "").trim())
        .filter((section) => COUNTRY_TEMPORARY_COMMENT_SECTIONS.has(section))
    );
    if (!sections.size) {
      return null;
    }
    return {
      sections,
      comment: getHeaderSignalsNote(source.comment)
    };
  }

  function isFranceCountryInfo(countryInfo) {
    const aliases = countryInfo && countryInfo.rule && Array.isArray(countryInfo.rule.aliases) ? countryInfo.rule.aliases : [];
    const values = [
      countryInfo && countryInfo.id,
      // canonicalName is the database name; displayName now carries the raw CRM text.
      countryInfo && countryInfo.canonicalName,
      countryInfo && countryInfo.displayName,
      countryInfo && countryInfo.rule && countryInfo.rule.country,
      ...aliases
    ];
    return values.some((value) => {
      const normalized = normalizeComparableText(value);
      return normalized === "fr" || normalized === "fra" || normalized === "france";
    });
  }

  function normalizeProductSkuValues(value) {
    if (value === null || value === undefined || value === "") {
      return [];
    }
    const values = Array.isArray(value)
      ? value
      : typeof value === "string" || typeof value === "number"
        ? String(value).split(/\r?\n/)
        : [];
    return Array.from(new Set(values.map((sku) => String(sku == null ? "" : sku).trim()).filter(Boolean)));
  }

  function resolveProductSkuValues(productRecord, countryInfo) {
    const raw = productRecord && productRecord.skus;
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
      return { values: [], scope: "" };
    }
    const canonical =
      Object.prototype.hasOwnProperty.call(raw, "global") ||
      Object.prototype.hasOwnProperty.call(raw, "regions") ||
      Object.prototype.hasOwnProperty.call(raw, "countries");
    const countries = canonical && raw.countries && typeof raw.countries === "object" && !Array.isArray(raw.countries)
      ? raw.countries
      : canonical
        ? {}
        : raw;
    const regions = canonical && raw.regions && typeof raw.regions === "object" && !Array.isArray(raw.regions)
      ? raw.regions
      : {};
    const countryId = countryInfo && countryInfo.id ? String(countryInfo.id) : "";
    const localValues = countryId ? normalizeProductSkuValues(countries[countryId]) : [];
    if (localValues.length) {
      return { values: localValues, scope: "country" };
    }
    const regionId = String(countryInfo && countryInfo.rule && countryInfo.rule.ga_zone || "").trim();
    const regionValues = regionId ? normalizeProductSkuValues(regions[regionId]) : [];
    if (regionValues.length) {
      return { values: regionValues, scope: "region" };
    }
    const globalValues = canonical ? normalizeProductSkuValues(raw.global) : [];
    return { values: globalValues, scope: globalValues.length ? "global" : "" };
  }

  function buildLocalProductServiceDetail(productId, countryInfo, productInfo, rules = localServiceRules) {
    const productRecord = rules.products && rules.products[productId];
    const productDisplay = rules.ids && rules.ids.products && rules.ids.products[productId];
    const zoneKey = countryInfo && countryInfo.rule && countryInfo.rule.ga_zone;
    const zoneRule = productRecord && productRecord.zones && zoneKey ? productRecord.zones[zoneKey] : null;
    const countryRule = (countryInfo && countryInfo.rule) || {};
    const countryRma = countryRule.rma || {};
    const countrySpare = countryRule.spare_parts || {};
    const productRma = (zoneRule && zoneRule.rma) || {};
    const productSpare = (zoneRule && zoneRule.spare_parts) || {};
    const countryRmaStatus = normalizeServiceStatus(countryRma.status);
    const countrySpareStatus = normalizeServiceStatus(countrySpare.status);
    const productRmaStatus = zoneRule ? normalizeServiceStatus(productRma.status) : null;
    const productSpareStatus = zoneRule ? normalizeServiceStatus(productSpare.status) : null;
    const missingGaProductRule = !productRecord || !zoneRule;
    const countryBlocksRma = isRestrictiveCountryStatus(countryRmaStatus);
    const countryBlocksSpare = isRestrictiveCountryStatus(countrySpareStatus);
    const countryImportant = getCountryTemporaryCommentOverride(countryRule);
    const productImportant = [getCountryTemporaryCommentOverride(productRecord), getCountryTemporaryCommentOverride(zoneRule)].filter(Boolean);
    const importantNotes = [
      ...(countryImportant ? [{ ...countryImportant, origin: "country" }] : []),
      ...productImportant.map((note) => ({ ...note, origin: "product" }))
    ];
    const temporarilyBlocks = (section) => importantNotes.some((note) => note.sections.has(section));
    // Older databases have no separate country Paid RMA / Exchange fields.
    const countryPaidStatus = normalizeServiceStatus(countryRule.paid_rma && countryRule.paid_rma.status);
    const countryBlocksPaid = countryPaidStatus === null ? countryBlocksRma : isRestrictiveCountryStatus(countryPaidStatus);
    const countryExchangeStatus = normalizeServiceStatus(countryRule.exchange && countryRule.exchange.status);
    const rmaUsesCountry = countryBlocksRma || (!missingGaProductRule && productRmaStatus === null);
    const spareUsesCountry = countryBlocksSpare || !zoneRule || productSpareStatus === null;
    const rmaStatus = missingGaProductRule && !countryBlocksRma ? null : rmaUsesCountry ? countryRmaStatus : productRmaStatus;
    const spareStatus = missingGaProductRule && !countryBlocksSpare ? null : spareUsesCountry ? countrySpareStatus : productSpareStatus;
    const priceCurrencyOverride = zoneKey === "usa" ? "USD" : "";
    const paid = productRma.paid || {};
    const countryTransportFee = productRma.extra_transport_fees && countryInfo ? productRma.extra_transport_fees[countryInfo.id] : null;
    const transportFee = formatServicePrice(countryTransportFee, priceCurrencyOverride) ? countryTransportFee : (productRma.default_transport_fee || null);
    const paidHasContent = !!(paid.location || formatServicePrice(paid.price, priceCurrencyOverride));
    const explicitPaidStatus = normalizeServiceStatus(paid.status);
    const paidStatus = missingGaProductRule ? null : explicitPaidStatus === null ? paidHasContent : explicitPaidStatus;
    const paidRepairAllowed = !countryBlocksPaid && !missingGaProductRule && (paidStatus === true || paidStatus === "temp");
    const paidRepairFrance = paidRepairAllowed && isFranceCountryInfo(countryInfo);
    const exchangeRule = zoneRule && zoneRule.exchange && typeof zoneRule.exchange === "object"
      ? zoneRule.exchange
      : null;
    const productExchangeStatus = String((exchangeRule && exchangeRule.status) || "").trim();
    const exchangeStatus = isRestrictiveCountryStatus(countryExchangeStatus)
      ? countryExchangeStatus === "temp" ? "temp" : "no"
      : missingGaProductRule ? "" : productExchangeStatus === "yes" ? (exchangeRule.destination || "yes") : productExchangeStatus;
    const exchangeComment = missingGaProductRule
      ? ""
      : getHeaderSignalsNote(exchangeRule && exchangeRule.comment);
    const skuData = resolveProductSkuValues(productRecord, countryInfo);
    const productNote = getHeaderSignalsNote([productRecord && productRecord.note, zoneRule && zoneRule.note].filter(Boolean).join("\n"));
    return {
      id: productId,
      dataMissing: missingGaProductRule,
      name: (productDisplay && productDisplay.name) || productId,
      zone: zoneKey || "",
      skus: skuData.values,
      skuScope: skuData.scope,
      rma: {
        value: rmaStatus,
        level: rmaUsesCountry ? "country" : "product",
        warranty: formatWarrantyDuration(countryRma.warranty_duration),
        location: getLocationLabel(productRma.location),
        paidLocation: paidRepairFrance ? "Carentoir" : paidRepairAllowed ? getLocationLabel(paid.location) : "",
        paidPrice: paidRepairAllowed ? formatServicePrice(paid.price, priceCurrencyOverride) : "",
        transportFee: paidRepairAllowed ? formatServicePrice(transportFee, priceCurrencyOverride) : "",
        paidStatus: countryBlocksPaid ? countryPaidStatus === "temp" ? "temp" : false : paidStatus
      },
      spareParts: {
        value: spareStatus,
        level: spareUsesCountry ? "country" : "product",
        warranty: formatWarrantyDuration(countrySpare.warranty_duration)
      },
      exchange: exchangeStatus,
      exchangeComment,
      temporaryOverride: {
        spareParts: temporarilyBlocks("spare_parts"),
        rma: temporarilyBlocks("rma"),
        paidRma: temporarilyBlocks("paid_rma"),
        exchange: temporarilyBlocks("exchange"),
        comment: importantNotes.map((note) => note.comment).filter(Boolean).join("\n")
      },
      importantNotes,
      productImportant: productImportant.length > 0,
      note: productNote
    };
  }

  function resolveLocalDocumentServiceData(country, productName) {
    const countryInfo = resolveLocalCountry(country);
    if (!countryInfo) {
      return null;
    }
    const productInfo = resolveLocalProductOrBundle(productName);
    if (!productInfo || !productInfo.productIds.length) {
      return {
        source: "local",
        country: countryInfo,
        product: null,
        productMissing: true,
        productDetails: [],
        spareParts: { value: null, level: "" },
        rma: { value: null, level: "" },
        note: ""
      };
    }
    if (productInfo.type === "bundle") {
      const details = productInfo.productIds.map((productId) => buildLocalProductServiceDetail(productId, countryInfo, productInfo));
      return {
        source: "local",
        country: countryInfo,
        product: productInfo,
        productDetails: details,
        bundleCountryOnly: true,
        spareParts: { value: combineServiceStatuses(details.map((detail) => detail.spareParts.value)), level: "country" },
        rma: { value: combineServiceStatuses(details.map((detail) => detail.rma.value)), level: "country" },
        note: getHeaderSignalsNote(countryInfo.rule.note)
      };
    }
    const details = productInfo.productIds.map((productId) => buildLocalProductServiceDetail(productId, countryInfo, productInfo));
    return {
      source: "local",
      country: countryInfo,
      product: productInfo,
      productDetails: details,
      spareParts: {
        value: combineServiceStatuses(details.map((detail) => detail.spareParts.value)),
        level: combineServiceLevels(details.map((detail) => detail.spareParts.level))
      },
      rma: {
        value: combineServiceStatuses(details.map((detail) => detail.rma.value)),
        level: combineServiceLevels(details.map((detail) => detail.rma.level))
      },
      note: getHeaderSignalsNote(details.map((detail) => detail.note).filter(Boolean).join("\n"))
    };
  }

  function getSignalValueLabel(value, labels) {
    if (value === true) {
      return labels.yes;
    }
    if (value === false) {
      return labels.no;
    }
    if (value === "temp") {
      return labels.temp;
    }
    return labels.unknown;
  }

  function formatExchangeStatus(value) {
    const normalized = normalizeComparableText(value);
    if (!normalized) {
      return "N/A";
    }
    if (normalized === "no") {
      return "No";
    }
    if (normalized === "yes") {
      return "Yes";
    }
    if (normalized === "both") {
      return "Retailer";
    }
    if (normalized === "retailer") {
      return "Retailer";
    }
    if (normalized === "us") {
      return "US";
    }
    return String(value || "").trim();
  }

  function formatServiceExchangeLabel(value, labels) {
    const status = String(value || "").trim().toLowerCase();
    if (status === "yes") return labels.yes;
    if (status === "no") return labels.no;
    if (status === "temp") return labels.temp;
    if (status === "both" || status === "retailer") return translateCairnContent("service.retailer", "Retailer");
    return status ? formatExchangeStatus(value) : labels.unknown;
  }
    installLocalServiceRulesFromCairmDb(db);
    return { resolve: resolveLocalDocumentServiceData, identityKey: normalizeLocalIdentityKey, resolveCountry: resolveLocalCountry, resolveProduct: resolveLocalProductOrBundle, rules: localServiceRules, formatWarrantyDuration, getSignalValueLabel, formatServiceExchangeLabel };
  }
  const api = { create, version: "0.48.0", sourceHash: "32611b56ad6b68ad482feaf01a30edc3eb65228f37f9f2407ad57ae5683d1218" };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.CairmAuditRuntime = api;
})(globalThis);
